baseURL = 'https://samsbp.github.io'
languageCode = 'en-us'
title = 'Xenophanes Musings'
theme = 'maverick'

[permalinks]
  pages = "/:slug"

[params]
  logo = '/assets/favicon.ico'
  description = "XenoPhanes Musings - Thinking from First Principles"
  items = 10

  [params.comments]
    enabled = true
    githubRepo = 'canhtran/maverick'
    theme = 'github-light'

  [params.author]
    email = 'samsbp18@gmail.com'
    name = 'Sam Benjamin Pragasam'


[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = "-110"
  [[menu.main]]
    identifier = "posts"
    name = "Post"
    url = "/posts/"
    weight = -200
  [[menu.main]]
    identifier = "book"
    name = "Book"
    url = "/book/"
    weight = -200

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 4

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS", "JSON"]
  pages = ["HTML", "RSS", "JSON"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

ignoreErrors = ["error-remote-getjson"]

copyright = '© Sam Benjamin Pragasam'
